# File: config.yml

game_screen:
  width: 800
  height: 600

game_mechanics:
  gravity: 5
  flap_strength: 20
  pipe_speed: 2
  pipe_width: 100
  pipe_gap: 200
  character_size: 50
  collision_penalty: -1  # Penalty for hitting a pipe
  pass_reward: 1          # Reward for successfully passing a pipe
  height_penalty: -0.1    # Penalty for flying too high or too low

initial_positions:
  character_x: 350
  character_y: 250
  pipe_x: 800
  pipe_height_min: 100
  pipe_height_max: 400

ai_config:
  epsilon: 0.3
  epsilon_min: 0.01
  epsilon_decay: 0.98
  gamma: 0.1
  learning_rate: 0.0001
  batch_size: 32
  buffer_size: 5000
  num_episodes: 50

other_settings:
  random_seed: 42

model:
  save_path: ./qmodel2.pth
  load_path: ~